### PR TITLE
Updated to version 5.2.0 and made necessary changes to updated library functions

### PR DESCRIPTION
**Pull request by cerberusv2px**
New version requires Module name so added that and other small changes that i encountered

### CODE REVIEW

**Review by JorgeCastilloPrz — CHANGES_REQUESTED** [review]
Thanks for your contribution :). Please could you reformat your code using the [SquareAndroid](https://github.com/square/java-code-styles/blob/master/configs/codestyles/SquareAndroid.xml ) code style? The one you're using makes some stuff appear on the diff that shouldn't.

**Comment by cerberusv2px** [comment]
Reformatter the entire project. Has solved some existing indentation. :)

**Comment by JorgeCastilloPrz** [comment]
The goal was to reduce the amount of lines on the diff here 😅. It's okay if you wanna do that but that would fit better on a different PR if possible. Pls just include here the files you touched but with the correct formatting.

**Comment by cerberusv2px** [comment]
I just imagined you giving yourself a huge face palm 😆

**Comment by cerberusv2px** [comment]
Files Changed:
1. ActivityModule.kt
2. AppModule.kt
3. InjectedActivity.kt
4. PhotosApp.kt
5. PhotoListActivity.kt

**Comment by cerberusv2px** [comment]
I will send new PR. Close this one.

**Comment by cerberusv2px** [comment]
I will send new PR. Close this one.

**Pull request closed without merging**
